#!/bin/bash

# Spice Up Your Spotify: A Beginner's Guide to Installing Spicetify on Arch Linux (Flatpak Edition)

# Function to print in purplish pink (custom color code)
pinkEcho() {
    echo -e "\033[38;5;199m$1\033[0m"
}

pinkEcho "Let's get started!"

# 1. Install curl
pinkEcho "Installing curl..."
sudo pacman -S curl --noconfirm

# 2. Install Spicetify
pinkEcho "Installing Spicetify..."
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh

# 3. Find Spotify's Flatpak path
pinkEcho "Locating Spotify's Flatpak directory..."
flatpak_path=$(flatpak --installations | grep com.spotify.Client | awk '{print $2}')

# 4. Construct the path to Spotify's files
spotify_path="x86_64/stable/active/files/extra/share/spotify"
full_spotify_path="$flatpak_path/$spotify_path"

# 5. Check if the constructed path exists
if [ ! -d "$full_spotify_path" ]; then
    pinkEcho "WARNING: Default Spotify path not found. Please check manually."
    # Script will continue, but you'll need to investigate the path manually.
else
    pinkEcho "Found Spotify at: $full_spotify_path"
fi

# 6. Find Spotify's preferences file (directly specifying path)
pinkEcho "Locating Spotify's preferences file..."
prefs_path=$(find ~/.var/app/com.spotify.Client/config/spotify -maxdepth 1 -name 'prefs' -type f)
pinkEcho "Found preferences file at: $prefs_path"

# 7. Configure Spicetify using awk (this step needs config-xpui.ini which is generated by `spicetify backup apply`)
pinkEcho "Configuring Spicetify..."
awk -v prefs_path="$prefs_path" '{ 
    if ($1 == "prefs_path") {
        $3 = prefs_path
    } 
    print $0
}' ~/.config/spicetify/config-xpui.ini > ~/.config/spicetify/config-xpui.ini.tmp
mv ~/.config/spicetify/config-xpui.ini.tmp ~/.config/spicetify/config-xpui.ini

# 8. Install Spicetify Marketplace
pinkEcho "Installing Spicetify Marketplace..."
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh | sh

# 9. Grant write permissions BEFORE `spicetify backup apply`
pinkEcho "Granting permissions to Spicetify..."
sudo chmod a+wr /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
sudo chmod a+wr -R /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps

# 10. Apply Spicetify 
pinkEcho "Applying Spicetify..."
spicetify backup apply 

pinkEcho "Done! Go forth and customize your Spotify experience!" 
